In [1]:
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\vj753\Downloads\Churn_Modelling.csv")

In [3]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [4]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [5]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,Female,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10002 non-null  int64
 1   Geography        10001 non-null  object
 2   Gender           10002 non-null  object
 3   Age              10001 non-null  float64
 4   Tenure           10002 non-null  int64
 5   Balance          10002 non-null  float64
 6   NumOfProducts    10002 non-null  int64
 7   HasCrCard        10001 non-null  float64
 8   IsActiveMember   10001 non-null  float64
 9   EstimatedSalary  10002 non-null  float64
 10  Exited           10002 non-null  int64
dtypes: float64(5), int64(4), object(2)
memory usage: 859.7+ KB

In [7]:
df=df.dropna()

In [8]:
df['Age']=df['Age'].astype('int64')
df['HasCrCard']=df['HasCrCard'].astype('int64')
df['IsActiveMember']=df['IsActiveMember'].astype('int64')

C:\Users\vj753\AppData\Local\Temp\ipykernel_21812\3106468823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].astype('int64')
C:\Users\vj753\AppData\Local\Temp\ipykernel_21812\3106468823.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['HasCrCard']=df['HasCrCard'].astype('int64')
C:\Users\vj753\AppData\Local\Temp\ipykernel_21812\3106468823.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['IsActiveMember']=df['IsActiveMember'].astype('int64')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9998 entries, 0 to 10001
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      9998 non-null   int64
 1   Geography        9998 non-null   object
 2   Gender           9998 non-null   object
 3   Age              9998 non-null   int64
 4   Tenure           9998 non-null   int64
 5   Balance          9998 non-null   float64
 6   NumOfProducts    9998 non-null   int64
 7   HasCrCard        9998 non-null   int64
 8   IsActiveMember   9998 non-null   int64
 9   EstimatedSalary  9998 non-null   float64
 10  Exited           9998 non-null   int64
dtypes: float64(2), int64(7), object(2)
memory usage: 937.3+ KB

In [10]:
df.corr()

C:\Users\vj753\AppData\Local\Temp\ipykernel_21812\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CreditScore,1.000000,-0.004235,0.000779,0.006580,0.012412,-0.005795,0.025125,-0.001256,-0.026790
Age,-0.004235,1.000000,-0.010116,0.028379,-0.030759,-0.011717,0.085486,-0.006949,0.285452
Tenure,0.000779,-0.010116,1.000000,-0.011986,0.013205,0.022557,-0.028090,0.007835,-0.014208
Balance,0.006580,0.028379,-0.011986,1.000000,-0.304163,-0.014678,-0.010323,0.012637,0.118564
NumOfProducts,0.012412,-0.030759,0.013205,-0.304163,1.000000,0.003368,0.009644,0.014378,-0.047621
HasCrCard,-0.005795,-0.011717,0.022557,-0.014678,0.003368,1.000000,-0.012039,-0.009924,-0.007023
IsActiveMember,0.025125,0.085486,-0.028090,-0.010323,0.009644,-0.012039,1.000000,-0.011022,-0.156072
EstimatedSalary,-0.001256,-0.006949,0.007835,0.012637,0.014378,-0.009924,-0.011022,1.000000,0.011981
Exited,-0.026790,0.285452,-0.014208,0.118564,-0.047621,-0.007023,-0.156072,0.011981,1.000000

In [72]:
#  gender_counts = df['Gender'].value_counts()
# plt.bar(gender_counts.index, gender_counts.values)
# plt.xlabel('Gender')
# plt.ylabel('Count')
# plt.title('Distribution of Gender')
# plt.show()

In [73]:
#  gender_counts = df['Geography'].value_counts()
# plt.bar(gender_counts.index, gender_counts.values)
# plt.xlabel('Geography')
# plt.ylabel('Geography')
# plt.title('Distribution of Gender')
# plt.show()

In [13]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1

In [14]:
df=pd.get_dummies(df,columns=['Gender'], prefix='Is',drop_first=True)

In [15]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Geography'] = label_encoder.fit_transform(df['Geography'])

In [16]:
df.head()

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Is_Male
0,619,0,42,2,0.00,1,1,1,101348.88,1,0
1,608,2,41,1,83807.86,1,0,1,112542.58,0,0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0
5,645,2,44,8,113755.78,2,1,0,149756.71,1,1

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [18]:
df[['scaled_Balance','scaled_EstimatedSalary','scaled_CreditScore','scaled_Age']]=scaler.fit_transform(df[['Balance','EstimatedSalary','CreditScore','Age']])

In [19]:
df.head()

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Is_Male,scaled_Balance,scaled_EstimatedSalary,scaled_CreditScore,scaled_Age
0,619,0,42,2,0.00,1,1,1,101348.88,1,0,-1.225860,0.021720,-0.326298,0.293666
1,608,2,41,1,83807.86,1,0,1,112542.58,0,0,0.117428,0.216366,-0.440137,0.198314
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0,1.333214,0.240519,-1.537125,0.293666
3,699,0,39,1,0.00,2,0,0,93826.63,0,0,-1.225860,-0.109083,0.501618,0.007611
5,645,2,44,8,113755.78,2,1,0,149756.71,1,1,0.597439,0.863478,-0.057226,0.484370

In [20]:
df.drop(['CreditScore','Age','Balance','EstimatedSalary'],axis=1,inplace=True)

In [21]:
x = df.drop('Exited', axis=1)
y = df['Exited']

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [23]:
print("Original training class distribution:", Counter(y_train))
print("Original testing class distribution:", Counter(y_test))

Original training class distribution: Counter({0: 6368, 1: 1630})
Original testing class distribution: Counter({0: 1592, 1: 408})

In [24]:
from imblearn.over_sampling import SMOTE

In [30]:
smote = SMOTE(random_state=42)

In [31]:
X_resampled, y_resampled = smote.fit_resample(x_train, y_train)

In [32]:
print("Resampled training class distribution:", Counter(y_resampled))

Resampled training class distribution: Counter({0: 6368, 1: 6368})

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [34]:

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [64]:
model=RandomForestClassifier(
    max_depth= 20,
    max_features= None,
    min_samples_leaf= 1,
    min_samples_split= 2,
    n_estimators= 1000,
    random_state=42,
    criterion= 'entropy')

In [65]:
model.fit(X_resampled, y_resampled)

RandomForestClassifier(criterion='entropy', max_depth=20, max_features=None,
                       n_estimators=1000, random_state=42)

In [67]:
y_pred=model.predict(x_test)

In [68]:
accuracy_score(y_pred,y_test)

0.831

In [71]:
# random_search.best_params_

In [76]:
import pickle

In [77]:
pickle.dump(model,open('model.pkl','wb'))