In [3]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\vj753\Downloads\Churn_Modelling.csv")

In [5]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [6]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1, inplace=True)

In [7]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,Female,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10002 non-null  int64
 1   Geography        10001 non-null  object
 2   Gender           10002 non-null  object
 3   Age              10001 non-null  float64
 4   Tenure           10002 non-null  int64
 5   Balance          10002 non-null  float64
 6   NumOfProducts    10002 non-null  int64
 7   HasCrCard        10001 non-null  float64
 8   IsActiveMember   10001 non-null  float64
 9   EstimatedSalary  10002 non-null  float64
 10  Exited           10002 non-null  int64
dtypes: float64(5), int64(4), object(2)
memory usage: 859.7+ KB

In [9]:
df=df.dropna()

In [10]:
df['Age']=df['Age'].astype('int64')

C:\Users\vj753\AppData\Local\Temp\ipykernel_18440\1560207250.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].astype('int64')

In [11]:
df['HasCrCard']=df['HasCrCard'].astype('int64')
df['IsActiveMember']=df['IsActiveMember'].astype('int64')
df['EstimatedSalary']=df['EstimatedSalary'].astype('int64')

C:\Users\vj753\AppData\Local\Temp\ipykernel_18440\3330023694.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['HasCrCard']=df['HasCrCard'].astype('int64')
C:\Users\vj753\AppData\Local\Temp\ipykernel_18440\3330023694.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['IsActiveMember']=df['IsActiveMember'].astype('int64')
C:\Users\vj753\AppData\Local\Temp\ipykernel_18440\3330023694.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EstimatedSalary']=df['EstimatedSalary'].astype('int64')

In [12]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542,0
2,502,France,Female,42,8,159660.80,3,1,0,113931,1
3,699,France,Female,39,1,0.00,2,0,0,93826,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756,1

In [13]:
df=pd.get_dummies(df,columns=['Gender'], prefix='Is',drop_first=True)

In [14]:
df

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Is_Male
0,619,France,42,2,0.00,1,1,1,101348,1,0
1,608,Spain,41,1,83807.86,1,0,1,112542,0,0
2,502,France,42,8,159660.80,3,1,0,113931,1,0
3,699,France,39,1,0.00,2,0,0,93826,0,0
5,645,Spain,44,8,113755.78,2,1,0,149756,1,1
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,36,7,0.00,1,0,1,42085,1,0
9998,772,Germany,42,3,75075.31,2,1,0,92888,1,1
9999,772,Germany,42,3,75075.31,2,1,0,92888,1,1
10000,792,France,28,4,130142.79,1,1,0,38190,0,0
10001,792,France,28,4,130142.79,1,1,0,38190,0,0

In [15]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [16]:
df['Geography'] = label_encoder.fit_transform(df['Geography'])

In [17]:
df

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Is_Male
0,619,0,42,2,0.00,1,1,1,101348,1,0
1,608,2,41,1,83807.86,1,0,1,112542,0,0
2,502,0,42,8,159660.80,3,1,0,113931,1,0
3,699,0,39,1,0.00,2,0,0,93826,0,0
5,645,2,44,8,113755.78,2,1,0,149756,1,1
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,0,36,7,0.00,1,0,1,42085,1,0
9998,772,1,42,3,75075.31,2,1,0,92888,1,1
9999,772,1,42,3,75075.31,2,1,0,92888,1,1
10000,792,0,28,4,130142.79,1,1,0,38190,0,0
10001,792,0,28,4,130142.79,1,1,0,38190,0,0

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [19]:
df[['scaled_Balance','scaled_EstimatedSalary','scaled_CreditScore','scaled_Age']]=scaler.fit_transform(df[['Balance','EstimatedSalary','CreditScore','Age']])

In [20]:
df

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Is_Male,scaled_Balance,scaled_EstimatedSalary,scaled_CreditScore,scaled_Age
0,619,0,42,2,0.00,1,1,1,101348,1,0,-1.225860,0.021714,-0.326298,0.293666
1,608,2,41,1,83807.86,1,0,1,112542,0,0,0.117428,0.216365,-0.440137,0.198314
2,502,0,42,8,159660.80,3,1,0,113931,1,0,1.333214,0.240518,-1.537125,0.293666
3,699,0,39,1,0.00,2,0,0,93826,0,0,-1.225860,-0.109085,0.501618,0.007611
5,645,2,44,8,113755.78,2,1,0,149756,1,1,0.597439,0.863474,-0.057226,0.484370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,709,0,36,7,0.00,1,0,1,42085,1,0,-1.225860,-1.008803,0.605107,-0.278445
9998,772,1,42,3,75075.31,2,1,0,92888,1,1,-0.022539,-0.125396,1.257091,0.293666
9999,772,1,42,3,75075.31,2,1,0,92888,1,1,-0.022539,-0.125396,1.257091,0.293666
10000,792,0,28,4,130142.79,1,1,0,38190,0,0,0.860094,-1.076532,1.464070,-1.041259
10001,792,0,28,4,130142.79,1,1,0,38190,0,0,0.860094,-1.076532,1.464070,-1.041259

In [21]:
df.drop(['CreditScore','Age','Balance','EstimatedSalary'],axis=1,inplace=True)

In [22]:
df

,Geography,Tenure,NumOfProducts,HasCrCard,IsActiveMember,Exited,Is_Male,scaled_Balance,scaled_EstimatedSalary,scaled_CreditScore,scaled_Age
0,0,2,1,1,1,1,0,-1.225860,0.021714,-0.326298,0.293666
1,2,1,1,0,1,0,0,0.117428,0.216365,-0.440137,0.198314
2,0,8,3,1,0,1,0,1.333214,0.240518,-1.537125,0.293666
3,0,1,2,0,0,0,0,-1.225860,-0.109085,0.501618,0.007611
5,2,8,2,1,0,1,1,0.597439,0.863474,-0.057226,0.484370
...,...,...,...,...,...,...,...,...,...,...,...
9997,0,7,1,0,1,1,0,-1.225860,-1.008803,0.605107,-0.278445
9998,1,3,2,1,0,1,1,-0.022539,-0.125396,1.257091,0.293666
9999,1,3,2,1,0,1,1,-0.022539,-0.125396,1.257091,0.293666
10000,0,4,1,1,0,0,0,0.860094,-1.076532,1.464070,-1.041259
10001,0,4,1,1,0,0,0,0.860094,-1.076532,1.464070,-1.041259

In [23]:
y=df['Exited']

In [24]:
y

0        1
1        0
2        1
3        0
5        1
        ..
9997     1
9998     1
9999     1
10000    0
10001    0
Name: Exited, Length: 9998, dtype: int64

In [25]:
x=df.drop(['Exited'],axis=1)

In [26]:
x

,Geography,Tenure,NumOfProducts,HasCrCard,IsActiveMember,Is_Male,scaled_Balance,scaled_EstimatedSalary,scaled_CreditScore,scaled_Age
0,0,2,1,1,1,0,-1.225860,0.021714,-0.326298,0.293666
1,2,1,1,0,1,0,0.117428,0.216365,-0.440137,0.198314
2,0,8,3,1,0,0,1.333214,0.240518,-1.537125,0.293666
3,0,1,2,0,0,0,-1.225860,-0.109085,0.501618,0.007611
5,2,8,2,1,0,1,0.597439,0.863474,-0.057226,0.484370
...,...,...,...,...,...,...,...,...,...,...
9997,0,7,1,0,1,0,-1.225860,-1.008803,0.605107,-0.278445
9998,1,3,2,1,0,1,-0.022539,-0.125396,1.257091,0.293666
9999,1,3,2,1,0,1,-0.022539,-0.125396,1.257091,0.293666
10000,0,4,1,1,0,0,0.860094,-1.076532,1.464070,-1.041259
10001,0,4,1,1,0,0,0.860094,-1.076532,1.464070,-1.041259

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [30]:

GB_model=GradientBoostingClassifier()

In [31]:

GB_model.fit(X_train,y_train)

GradientBoostingClassifier()

In [32]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import GradientBoostingRegressor
from scipy.stats import randint, uniform

In [33]:
param_grid = {
    'n_estimators': randint(50, 200),  # Integers between 50 and 199
    'learning_rate': uniform(0.01, 0.2), # Uniform distribution between 0.01 and 0.21
    'max_depth': randint(3, 10),       # Integers between 3 and 9
    'subsample': uniform(0.7, 0.3),    # Uniform distribution between 0.7 and 1.0
    'min_samples_split': randint(2, 11), # Integers between 2 and 10
    'min_samples_leaf': randint(1, 5)   # Integers between 1 and 4
}

In [34]:
from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(
    estimator=GB_model,
    param_distributions=param_grid,
    n_iter=30,  # Only test 30 random combinations
    scoring='f1',
    cv=3,
    n_jobs=-1,
    verbose=2,
    random_state=42
)

In [35]:
random_search.fit(X_train, y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

RandomizedSearchCV(cv=3, estimator=GradientBoostingClassifier(), n_iter=30,
                   n_jobs=-1,
                   param_distributions={'learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x00000284FC387690>,
                                        'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000284FC824750>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure....00000284FC825790>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000284FC825190>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000284FC817110>,
                                        'subsample': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x00000284FC824CD0>},
                   random_state=42, scoring='f1', verbose=2)

In [36]:
print("Best Parameters:", random_search.best_params_)

Best Parameters: {'learning_rate': 0.11401360423556216, 'max_depth': 4, 'min_samples_leaf': 4, 'min_samples_split': 7, 'n_estimators': 195, 'subsample': 0.9325398470083344}

In [37]:
gb_final = GradientBoostingClassifier(
    subsample=0.7,
    n_estimators=300,
    min_samples_split=5,
    min_samples_leaf=3,
    max_depth=5,
    learning_rate=0.05,
    random_state=42
)

gb_final.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.05, max_depth=5, min_samples_leaf=3,
                           min_samples_split=5, n_estimators=300,
                           random_state=42, subsample=0.7)

In [38]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = gb_final.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Accuracy: 0.864
Precision: 0.7428571428571429
Recall: 0.5098039215686274
F1 Score: 0.6046511627906976

In [39]:
import pickle

In [40]:
pickle.dump(gb_final,open('model.pkl','wb'))

In [41]:
temp_test=np.array([])

NameError: name 'np' is not defined